app/routes.py
import copy
from io import BytesIO
import os
from functools import wraps
import random
import secrets
import clamd  
import uuid
import magic


from flask import current_app as app, request, send_from_directory
from flask import abort, Blueprint, render_template, redirect, url_for, flash
from flask import Markup
from flask_limiter.util import get_remote_address
from flask_login import login_user, logout_user, current_user, login_required
from flask_mail import Message
from itsdangerous import BadSignature, SignatureExpired, URLSafeTimedSerializer

from werkzeug.utils import secure_filename

from app import db, limiter, logger, mail, login_manager
from app.forms import OTPForm, RegisterForm, LoginForm, FeedbackForm, UserToggleForm
from app.models import Honeypot, User, Feedback




@login_manager.user_loader
def load_user(user_id):
    return User.get_user(user_id)


# Initialize ClamAV scanner
clamd_socket = '/var/run/clamav/clamd.ctl'  # Adjust the socket path based on your ClamAV configuration
clamav = clamd.ClamdUnixSocket()


# Rate Limiter
# limiter.init_app(app)

# Admin required decorator
def admin_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if not current_user.is_admin:
            flash('You are not authorized to access this page.', 'danger')
            return render_template('error.html', error_code=500), 500
        return f(*args, **kwargs)
    return decorated_function

def otp_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if not current_user.otp_verified:
            flash('You are not authorized to access this page.', 'danger')
            return render_template('error.html', error_code=500), 500
        return f(*args, **kwargs)
    return decorated_function

# Function to generate a verification token
def generate_verification_token(username):
    # Generate the verification token

    with app.app_context():
        serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])

        token = serializer.dumps(username, salt='email-verification')  # Token expires after 1 hour (3600 seconds)
        return token

# Function to send a verification email
def send_verification_email(email, verification_link):
    msg = Message('Account Verification', recipients=[email], sender= os.getenv('MAIL_DEFAULT_SENDER'))
    msg.body = f'Please click on the link below to verify your account:\n{verification_link}'
    # txt = f'Please click on the link below to verify your account:\n{verification_link}'
    # mail.send_message(recipients=[email], body=txt, subject='Account Verification',sender= os.getenv('MAIL_USERNAME'))
    mail.send(msg)


def send_OTP(user):
    user.pincode = random.randint(100000, 999999)
    user.save()
    msg = Message('OTP', recipients=[user.email], sender= os.getenv('MAIL_DEFAULT_SENDER'))
    msg.body = f'Your OTP is {user.pincode}'
    mail.send(msg)



main = Blueprint('main', __name__,url_prefix='/')



# Routes

@main.route('/')
def index():
    return render_template('index.html')

@main.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if request.method == 'GET':
        return render_template('register.html', form=form)

    if form.validate_on_submit():
        username = form.username.data
        email = form.email.data
        password = form.password.data
        name = form.name.data

        # Check if user already exists
        if User.query.filter_by(username=username).first():
            flash('Username already taken. Please choose a different username.', 'danger')
            logger.error('Username already taken: {}'.format(username))
            return redirect(url_for('main.register'))

        # Check if email is  already taken
        if User.query.filter_by(email=email).first():
            flash('Email already taken. Please choose a different email.', 'danger')
            logger.error('Email already taken: {}'.format(email))
            return redirect(url_for('main.register'))

        # Send verification email
        token = generate_verification_token(username)
        verification_link = url_for('main.verify_email', token=token, _external=True)
        send_verification_email(email, verification_link)

        # Create a new user
        user = User(username=username, email=email, name = name)
        user.set_password(password)
        user.save()

        logger.info('User registered: {}'.format(username))


        flash('Registration successful. Please check your email to verify your account.', 'success')
        return redirect(url_for('main.login'))
    else:
        errors = form.errors
        for key, val in errors.items():
            for err in val:
                flash(err, 'danger')
                
        return redirect(url_for('main.register'))
        # flash(form.errors, 'danger')



@main.route('/verify/<token>')
def verify_email(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.dashboard'))
    try:
        with app.app_context():
            serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])

            username = serializer.loads(token, salt='email-verification', max_age=3600)  # Token expires after 1 hour (3600 seconds)
            user = User.query.filter_by(username=username).first()
            if user:
                user.is_verified = True
                user.save()
                logger.info('Email verified for user: {}'.format(username))
                flash('Email verification successful. You can now log in.', 'success')
            else:
                flash('Invalid verification token.', 'danger')
    except SignatureExpired:
        flash('Verification token has expired.', 'danger')
    except BadSignature:
        flash('Invalid verification token.', 'danger')

    flash('Account verified successfully. You can now log in.', 'success')
    return redirect(url_for('main.login'))

@login_required
@main.route('/otp', methods=['GET', 'POST'])
def otp():
    if current_user.is_authenticated and current_user.otp_verified:
        return redirect(url_for('main.dashboard'))
    form = OTPForm()
    if request.method == 'GET':
        return render_template('otp.html', form=form)
    if form.validate_on_submit():
        otp = form.otp.data
        user = User.query.filter_by(username=current_user.username).first()
        if user.pincode == otp:
            user.otp_verified = True
            user.pincode = None
            user.save()
            flash('OTP verified successfully. You can now log in.', 'success')
            return redirect(url_for('main.login'))
        
        flash('Incorrect Pin Code', 'danger')

    else:
        errors = form.errors
        for key, val in errors.items():
            for err in val:
                flash(err, 'danger')
    return redirect(url_for('main.otp'))
    


# @limiter.limit("5/minute")  # Rate limit: 5 requests per minute
@main.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.dashboard'))
    
    form = LoginForm()
    if request.method == 'GET':
        return render_template('login.html', form=form)
    
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data

        user = User.query.filter_by(username=username).first()
       

            
        if user and not user.is_verified:
            flash('Please Verify Email', 'warning')

        if user and  user.is_blocked:
            flash('You are Blocked by the admin of this site please contact Admin.', 'warning')
            logger.error('User blocked: {}'.format(username))
    
        elif user and user.check_password(password):
            login_user(user)

            
            flash('OTP sent!', 'success')
            logger.info('User logged in: {}'.format(username))
            send_OTP(user)
            return redirect(url_for('main.otp'))
        else:
            flash('Invalid username or password. Please try again!', 'warning')
            logger.error('Invalid credentials entered for user: {}'.format(username))
            
        return redirect(url_for('main.login'))

    if form.errors:
        for key, val in form.errors.items():
            for err in val:
                flash(err, 'danger')
    
    return redirect(url_for('main.login'))



@main.route('/logout')
@login_required
def logout():
    logger.info('User logged out: {}'.format(current_user.username))
    current_user.otp_verified = False
    current_user.save()
    logout_user()
    flash('You have been logged out.', 'info')
    return redirect(url_for('main.index'))

@main.route('/dashboard')
@login_required
@otp_required
def dashboard():
    
    if current_user.is_admin:
        feedbacks = Feedback.query.all()
    else:
        
        feedbacks = Feedback.query.filter_by(user_id=current_user.id).all()

    form = FeedbackForm() 
    return render_template('dashboard.html', feedbacks=feedbacks, form = form)

@main.route('/secret')
@login_required
@otp_required
@admin_required
def admin():
    members = User.query.all()
    form = UserToggleForm()
    return render_template('admin.html', members=members, form = form)


# Route for enabling/disabling user accounts (admin only)
@main.route('/admin/user/<int:user_id>/toggle_status', methods=['POST'])
@login_required
@otp_required
def toggle_user_status(user_id):
    if not current_user.is_admin:
        abort(403)  # Only admin can access this route

    user = User.query.get_or_404(user_id)
    if user == current_user:
        flash('Cannot disable your own account.', 'danger')
    else:
        user.is_blocked = not user.is_blocked
        user.save()
        logger.info('User status toggled by admin. User ID: {}, Status: {}'.format(user_id, user.is_active))
        flash('User account status updated.', 'success')

app/templates/admin.html
{% extends 'base.html' %}

{% block title %}Admin Dashboard{% endblock %}

{% block content %}
  <div class="container">
    <h2 class="text-center">Admin Dashboard</h2>
    <div class="row justify-content-center">
      <div class="col-md-6">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>User ID</th> 
              <th>Username</th>
              <th>Email</th>
              <th>Status</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {% for user in members %}
            <tr>
              <td>{{ user.id }}</td>
              <td>{{ user.username }}</td>
              <td>{{ user.email }}</td>
              <td>
                {% if not user.is_active %}
                  Disabled
                {% else %}
                  Enabled
                {% endif %}
              </td>
              <td>
                <form method="POST" action="{{ url_for('main.toggle_user_status', user_id=user.id) }}">
                  {{ form.hidden_tag() }}


                {% if not user.is_verified %}
                  <button class="btn btn-success" type="submit">Enable</button>
                {% else %}
                  <button class="btn btn-danger" type="submit">Disable</button>
                {% endif %}
              </form>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <style>
    /* Custom styles */
  
    .form-label {
      font-weight: bold;
    }
  </style>
  {% block styles %}{% endblock %}
</head>
<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-primary">
    <div class="container">
      <a class="navbar-brand" href="{{ url_for('main.index') }}">Feedback FORM</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('main.dashboard') }}">Dashboard</a>
            </li>
            {%if current_user.is_admin %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('main.admin') }}">Admin</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('main.view_honeypot') }}">Honeypots</a>
            </li>
            {%endif%}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('main.logout') }}">Logout</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('main.login') }}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('main.register') }}">Register</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    <div class="container mt-4">
      {% for category, message in messages %}
        <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% endfor %}
    </div>
  {% endif %}
{% endwith %}


  {% block content %}{% endblock %}

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  {% block scripts %}{% endblock %}
</body>
</html>

app/templates/dashboard.html
{% extends 'base.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}

  <div class="container mt-4">
    <h2>Welcome, {{ current_user.username }}</h2>
      <!-- Plus Icon Button -->
  <div class="container mt-4">
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#feedbackModal">
      <i class="fas fa-plus"></i> Add Feedback
    </button>
  </div>
  {%if current_user.is_admin%}
  <h3>Feedbacks</h3>
  {%else%}
  <h3>Your Feedbacks</h3>
  {%endif%}
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Feedback ID</th>
          <th>Name</th>
          <th>Email</th>
          <th>Comments</th>
          <th>File</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        {% for feedback in feedbacks %}
        <tr>
          <td>{{ feedback.id }}</td>
          <td>{{ feedback.user.name }}</td>
          <td>{{ feedback.user.email }}</td>
          <td>{{ feedback.comment }}</td>
          {% if feedback.file %}

          <td><a href="{{ url_for('main.files_uploaded', filename=feedback.file) }}" target="_blank">{{ feedback.real_file_name }}</a></td>
          {% else %}
          <td>No file uploaded</td>
          {% endif %}


          <td>
            {% if feedback.user_id == current_user.id %}
            <a href="{{ url_for('main.edit_feedback', feedback_id=feedback.id) }}" class="btn btn-primary btn-sm">Edit</a>

            {%endif%}
            
            <button class="btn btn-danger" data-toggle="modal" data-target="#deleteModal">Delete</button>

         
          </td>
        </tr>
        <!-- Delete Modal -->
        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Confirm Deletion</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <p>Are you sure you want to delete this feedback?</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <form action="{{ url_for('main.delete_feedback', feedback_id=feedback.id) }}" method="POST">
                  {{ form.hidden_tag() }}
                  <button type="submit" class="btn btn-danger">Delete</button>
                </form>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </tbody>
    </table>
  </div>


  <!-- Feedback Modal -->
  <div class="modal fade" id="feedbackModal" tabindex="-1" role="dialog" aria-labelledby="feedbackModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="feedbackModalLabel">Add Feedback</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form method="POST" action="{{ url_for('main.feedback') }}" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <div class="form-group">
              {{ form.comment.label }} {{ form.comment(class="form-control") }}
            </div>
            <div class="form-group">
              {{ form.file.label }} {{ form.file(class="form-control-file") }}
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              {{ form.submit(class="btn btn-primary") }}
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

app/templates/edit_feedback.html
{% extends 'base.html' %}

{% block title %}Edit Feedback{% endblock %}

{% block content %}
  <div class="container">
    <h2 class="text-center">Edit Feedback</h2>
    <div class="row justify-content-center">
      <div class="col-md-6">
        <form method="POST" enctype="multipart/form-data">
          {{ form.csrf_token }}
         
          <div class="form-group">
            <label for="comments">Comment</label>
            <textarea class="form-control" id="comment" name="comment" rows="5" required>{{ feedback.comment }}</textarea>
          </div>
          <div class="form-group">
            <label for="file">File (PDF only)</label>
            <div>
              {% if feedback.file %}
                <td><a href="{{ url_for('main.files_uploaded', filename=feedback.file) }}" target="_blank">{{ feedback.real_file_name }}</a></td>
              {% else %}
                <td>No file uploaded</td>
              
              {% endif %}
              <input type="file" class="form-control-file" id="file" name="file">
            </div>
                   </div>
          <div class="form-group">
            <button type="submit" class="btn btn-primary">Update Feedback</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/error.html
{% extends 'base.html' %}


{% block styles %}
  <title>Error</title>
  <style>
    body {
            background-color: #f4f4f4;

            height: 100vh;
        }

        .content {
            text-align: center;
        }

        h1 {
            font-size: 40px;
            color: #333;
            margin-bottom: 20px;
        }

        img {
            max-width: 400px;
            height: auto;
        }
    </style>
    {% endblock styles %}
    {% block content %}
    <div class="content">
        <h1>Error!</h1>
        <p>An error occurred while processing your request.</p>

        {% if error_code == 401 %}
        <p>You are not authorized to access this page.</p>
        <img src="{{ url_for('static', filename='images/error.png') }}" alt="Unauthorized">
      {% elif error_code == 403 %}
        <p>Access to this page is forbidden.</p>
        <img src="{{ url_for('static', filename='images/error.png') }}" alt="Forbidden">
      {% elif error_code == 404 %}
        <p>The requested page could not be found.</p>
        <img src="{{ url_for('static', filename='images/404.jpg') }}" alt="Not Found">
      {% elif error_code == 500 %}
        <p>An internal server error occurred.</p>
        <img src="{{ url_for('static', filename='images/500.jpg') }}" alt="Internal Error">
      {% else %}
        <p>Please try again later.</p>
        <img src="{{ url_for('static', filename='images/error.png') }}" alt="Error">
      {% endif %}
    </div>
    {% endblock %}

app/templates/honeypot.html
{% extends 'base.html' %}

{% block content %}
  <h1>Honeypot List</h1>
  
  <table class="table table-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th>IP</th>
        <th>User Agent</th>
        <th>Headers</th>
        <th>Attempted at At</th>
      </tr>
    </thead>
    <tbody>
      {% for item in honeypots %}
        <tr>
          <td>{{ item.id }}</td>
          <td>{{ item.ip }}</td>
          <td>{{ item.user_agent }}</td>
          <td>
            {% if item.headers|length > 50 %}
              <span class="truncated-headers"  title="{{ item.headers }}">{{ item.headers[:50] }}...</span>
            {% else %}
              {{ item.headers }}
            {% endif %}
          </td>
          <td>{{ item.created_at.strftime('%Y-%m-%d %H:%M:%S') }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <script>
    document.querySelectorAll('.truncated-headers').forEach(function(element) {
      element.addEventListener('click', function() {
        var fullHeaders = this.getAttribute('title');
        var isExpanded = this.getAttribute('data-expanded') === 'true';
  
        if (isExpanded) {
          this.innerHTML = fullHeaders.substring(0, 50) + '...';
          this.setAttribute('data-expanded', 'false');
        } else {
          this.innerHTML = fullHeaders;
          this.setAttribute('data-expanded', 'true');
        }
      });
    });
  </script>
  
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
  <div class="container">
    <div class="jumbotron mt-4">
      <h1 class="display-4">Welcome to Feedback Form</h1>
      <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
      <hr class="my-4">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut a urna nec leo sagittis eleifend. Nullam iaculis, justo eget fermentum ultrices, enim odio iaculis purus, in luctus ipsum metus sed est.</p>
      <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
    </div>
  </div>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="container">
  <h2 class="text-center">Login</h2>
  <div class="row justify-content-center">
    <div class="col-md-6">
      <form method="POST">
        {{ form.csrf_token }}
        <div class="form-group">
          {{ form.username.label(class="form-label") }}
          {{ form.username(class="form-control") }}
        </div>
        <div class="form-group">
          {{ form.password.label(class="form-label") }}
          {{ form.password(class="form-control", autocomplete='off') }}
        </div>
 
        <div class="form-group">
        {{form.captcha}}  
        </div>  
        <button type="submit" class="btn btn-primary">Login</button>

      </form>
    </div>
  </div>
</div>
{% endblock %}

app/templates/otp.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>OTP</h1>
    <form method="POST">
        {{ form.csrf_token }}
        <div class="form-group">
          {{ form.otp.label }} {{ form.otp( class="form-control") }}
    
        </div>
        <div class="form-group">
          {{ form.submit(class="btn btn-primary") }}
        </div>
      </form>
</div>
{% endblock %}

app/templates/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block content %}
<div class="container">
  <h2 class="text-center">Register</h2>
  <div class="row justify-content-center">
    <div class="col-md-6">
      <form method="POST">
        {{ form.csrf_token }}
        <div class="form-group">
          {{ form.username.label(class="form-label") }}
          {{ form.username(class="form-control") }}
        </div>

        <div class="form-group">
          {{ form.name.label(class="form-label") }}
          {{ form.name(class="form-control") }}
        </div>
        <div class="form-group">
          {{ form.email.label(class="form-label") }}
          {{ form.email(class="form-control") }}
        </div>
        <div class="form-group">
          {{ form.password.label(class="form-label") }}
          {{ form.password(class="form-control" , autocomplete='off') }}
        </div>
        <div class="form-group">
          {{ form.confirm_password.label(class="form-label") }}
          {{ form.confirm_password(class="form-control" , autocomplete='off') }}
        </div>

        

        <div class="form-group">
          {{form.captcha}}  
          </div>  
 
        <button type="submit" class="btn btn-primary">Register</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}